name: Andy Leggett - A full stack web application developer based in Stirling, Scotland
markdown: redcarpet
highlighter: true
exclude: ['node_modules', 'sass','.sass-cache','gulpfile.js','config.rb','package.json','README.md']
permalink: pretty