name: Andy Leggett - A full stack web application developer based in Stirling, Scotland
markdown: redcarpet
pygments: true
exclude: ['node_modules', 'sass','.sass-cache','Gruntfile.js','config.rb','package.json','*.sublime*','bower.json','README.md']
permalink: pretty